# Generated by Django 2.1.2 on 2018-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('motivo', models.TextField(null=True)),
                ('imagen', models.FileField(max_length=250, null=True, upload_to='storage/images/')),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
    ]
